### ISSUE TITLE
build assimp from issue 4 branch doesn't work.

### ISSUE THREAD

**Issue by johnfoundations** [3drepo/assimp#8]
As per https://github.com/3drepo/3drepobouncer/wiki/Compiling-ASSIMP, i switched to branch ISSUE_4 and downloaded zip. Cmake worked, but make failed as follows:

/home/john/3dr/assimp-ISSUE_4/code/MultiPartOptim.cpp:638:49: error: in C++98 ‘iVertices’ must be initialized by constructor, not by ‘{...}’
   std::vector<unsigned int>  iVertices = { 0, 0 };
                                                 ^
/home/john/3dr/assimp-ISSUE_4/code/MultiPartOptim.cpp:639:46: error: in C++98 ‘iFaces’ must be initialized by constructor, not by ‘{...

**Comment by johnfoundations** [comment]
The master branch fails with the same problem.

**Comment by carmenfan** [comment]
Hi John,

You need a C++11 compatible compiler to build this. I'd suggest GCC 4.9 or higher as 3drepobouncer would require the std::regex api, which is only available from 4.9 onwards.
